#!/usr/bin/python

import cStringIO as StringIO
import collections
from fnmatch import fnmatch
import difflib
import pprint
import os
import re
import sys
import simplejson


def get_name(filename):
    return os.path.splitext(filename)[0]


def list_dir(dir_path, filter_func):
    return sorted(filter(filter_func, os.listdir(dir_path)), key=get_name)


def main():
    test_dir = os.path.dirname(os.path.realpath(__file__))
    testcase_dir = os.path.join(test_dir, 'testcases')
    testcase_file = os.path.join(test_dir, 'testcases.js')
    expected_failures_file = os.path.join(test_dir, 'expected_failures.js')

    def is_testcase_file(filename):
        return (
            fnmatch(filename, "*.html") and
            not fnmatch(filename, "manual-test*") and
            not fnmatch(filename, "disabled-*"))

    failures = collections.defaultdict(lambda: 0)
    for f in list_dir(testcase_dir, is_testcase_file):
       failures['all'] += 1
       if f == "unit-test-testharness-failure.html":
          continue
       m = re.search(
          r'var expected_failures = ({[^;]*);',
          open(os.path.join(testcase_dir, f)).read())

       if m:
          test_failures = re.findall('{[^}]*}', m.groups()[0][1:-1])

          # Strip out the messages
          fails_on = {}
          for i, test_failure in enumerate(test_failures):
            for key, value in re.findall('([^:]*):(.*)', test_failure[1:-1]):
              key = key.strip()
              value = value.strip()

              if key.strip() == 'message':
                continue

              if value[-1] == ',':
                value = value[:-1]
              fails_on[key] = value
          for failure in fails_on:
             failures[failure] += 1
          print f, ' ',
          pprint.pprint(fails_on)
    pprint.pprint(dict(failures))


    new_testcases = StringIO.StringIO()
    new_testcases.write("""\
// This file is automatically generated by test/update-testcases.py.
// Disable tests by adding them to test/disabled-testcases
""")
    new_testcases.write('var tests = [\n  \'')
    new_testcases.write(
        '\',\n  \''.join(list_dir(testcase_dir, is_testcase_file)))
    new_testcases.write('\',\n];\n')
    new_testcases.seek(0)
    new_testcases_lines = new_testcases.readlines()

    current_testcases_lines = file(testcase_file).readlines()

    lines = list(difflib.unified_diff(
        current_testcases_lines, new_testcases_lines,
        fromfile=testcase_file, tofile=testcase_file))

    if len(lines) == 0:
        sys.stdout.write('Nothing to do\n')
        sys.exit(0)

    if not "--dry-run" in sys.argv:
        file(testcase_file, "w").write("".join(new_testcases_lines))
        sys.stdout.write(
            'Updating %s with the following diff.\n' % testcase_file)

    for line in lines:
        sys.stdout.write(line)

    sys.exit(1)


if __name__ == '__main__':
    main()
